<?php

namespace App\enums;

enum UserRoles
{
   CONST CLIENT = "CLIENT";
   CONST SUPERADMIN = "SUPERUSER";
   CONST ADMIN = "ADMIN";
   CONST FREELANCER = "FREELANCER";
   CONST SUPPORT = "SUPPORT";
}
